# Generated by Django 5.1.1 on 2024-09-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pinjamBuku", "0003_transactionborrowbook_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionborrowbook",
            name="admin",
            field=models.IntegerField(default=-2),
        ),
    ]
