# Generated by Django 5.1.1 on 2024-10-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pinjamBuku", "0004_alter_transactionborrowbook_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
        migrations.AddField(
            model_name="borrower",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
    ]
